/* @flow */
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';
export const FETCH_ITEMS_LOADING = 'FETCH_ITEMS_LOADING';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const SET_TAG = 'SET_TAG';
export const SORT_LIKES_BY = 'SORT_LIKES_BY';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_AUTHENTICATION_STATUS = 'SET_AUTHENTICATION_STATUS';
export const SET_AUTHENTICATION_TOKEN = 'SET_AUTHENTICATION_TOKEN';
